#!/usr/bin/sh

LIBRARY_FILE=/usr/lib64/libabrt-java-connector.so
STATE_FILE=/var/run/abrt/abrt-java.run

case "$1" in
    "start")
        ln -sf $LIBRARY_FILE $STATE_FILE
        RETVAL=$?
        ;;
    "stop")
        rm -f $STATE_FILE
        RETVAL=$?
        ;;
    "status")
        if [ -e $STATE_FILE ]
        then
            RETVAL=0;
        else
            RETVAL=3;
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status}"
        RETVAL=2
        ;;
esac

exit $RETVAL
