/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExceptionCaugthInNative */

#ifndef _Included_ExceptionCaugthInNative
#define _Included_ExceptionCaugthInNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExceptionCaugthInNative
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ExceptionCaugthInNative_nativeMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
