.\" Process this file with
.\" groff -man -Tascii bugzilla_format_java.conf.5
.\"
.TH BUGZILLA_FORMAT_JAVA.CONF 5 "JULY 2013" "abrt-java-connector" "User Manuals"
.SH "NAME"
bugzilla_format_java.conf \- configuration file for libreport\&.
.SH "DESCRIPTION"
.sp
This configuration file provides definition of formatting for new Bugzilla bugs for \fIJava excecptions\fR\&.
.SH "SEE ALSO"
.sp
reporter\-bugzilla(1), java_event\&.conf(5)
.SH "AUTHOR"
Jakub Filak <jfilak at redhat dot com>
.RE
