.\" Process this file with
.\" groff -man -Tascii bugzilla_formatdup_java.conf.5
.\"
.TH BUGZILLA_FORMATDUP_J.CONF "5" "JULY 2013" "abrt-java-connector" "User Manuals"
.SH "NAME"
bugzilla_formatdup_java.conf \- configuration file for libreport\&.
.SH "DESCRIPTION"
.sp
This configuration file provides definition of formatting for additional comments of Bugzilla bugs for \fIJava exceptions\fR\&.
.SH "SEE ALSO"
.sp
reporter\-bugzilla(1), java_event\&.conf(5)
.SH "AUTHOR"
Jakub Filak <jfilak at redhat dot com>
.RE
