.\" Process this file with
.\" groff -man -Tascii java_event.conf.5
.\"
.TH JAVA_EVENT.CONF 5 "JULY 2013" abrt-java-connector "User Manuals"
.SH NAME
java_event.conf \- configuration file for libreport\&.
.SH DESCRIPTION
.sp
This configuration file provides definitions of events for Java exception\&.
.sp
By default the file contains definition for \fIpost-create\fR and \fIreport-gui\fR events.
.SH AUTHOR
Jakub Filak <jfilak at redhat dot com>
.SH "SEE ALSO"
.BR report_event.conf (5)
