.\" Process this file with
.\" groff -man -Tascii java_event_fedora.conf.5
.\"
.TH java_event_fedora.conf 5 "JULY 2013" abrt-java-connector "User Manuals"
.SH NAME
java_event_fedora.conf \- configuration file for libreport\&.
.SH DESCRIPTION
.sp
This configuration file provides definitions of events for Java exception problems\&.
.sp
By default the file contains definition for \fIreport-cli\fR, \fIpost-report\fR, \fIreport_uReport\fR and \fIreport_Bugzilla\fR events\&.
.SH AUTHOR
Jakub Filak <jfilak at redhat dot com>
.SH "SEE ALSO"
.BR report_event.conf (5)
