.\" Process this file with
.\" groff -man -Tascii report_java_rhel.conf.5
.\"
.TH REPORT_JAVA_RHEL.CONF 5 "JULY 2013" "abrt-java-connector" "User Manuals"
.SH NAME
report_java_rhel.conf \- configuration file for libreport\&.
.SH "DESCRIPTION"
.sp
This configuration file specifies which of the reporting work flow definitions are applicable for Java problems types on Red Hat Enterprise Linux\&.
.sp
All applicable reporting work flows are presented to users in User Interface as possibilities for processing of a particular problem\&.
.sp
This configuration file consists from one condition per line\&.
.sp
Each condition line must start with EVENT=workflow_NAME where "workflow_" is constant prefix and "workflow_NAME" is base name of path to reporting work flow configuration file\&.
.sp
The rest of condition line has form VAR=VAL, VAR!=VAL or VAL~=REGEX, where VAR is a name of problem directory element to be checked (for example, "executable", "package", hostname" etc)\&. The condition may consists from as many element checks as it is necessary\&.
.SH "EXAMPLES"
.PP
Condition line
.RS 4
EVENT=workflow_RHELJava analyzer=Java
.RE
.sp
The condition line above expects existence of /usr/share/libreport/workflows/workflow_RHELJava\&.xml
.SH "SEE ALSO"
.sp
report\-gtk(1)
.SH AUTHOR
Jakub Filak <jfilak at redhat dot com>
.SH "SEE ALSO"
.BR report_event.conf (5)
